apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-depl
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: member
  template:
    metadata:
      labels:
        app: member
    spec:
      containers:
        - name: member-container
          image: 221082171363.dkr.ecr.ap-southeast-2.amazonaws.com/member-service:latest
          ports:
            - containerPort: 8080

          resources:
            limits:
              cpu: "1"
              memory: "500Mi"
            requests:
              cpu: "0.5"
              memory: "250Mi"

          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: my-app-secrets   # ⚠️ 이거 아래랑 다름
                  key: DB_HOST
            - name: DB_PW
              valueFrom:
                secretKeyRef:
                  name: my-app-secrets   # ⚠️ 하이픈 vs 언더스코어 확인 필요
                  key: DB_PW

          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: member-service
  namespace: dev
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: member



