apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-depl
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
        - name: apigateway-container
          image: 221082171363.dkr.ecr.ap-southeast-2.amazonaws.com/apigateway:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: "500Mi"
            requests:
              cpu: "0.5"
              memory: "250Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: apigateway-service
  namespace: dev
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: apigateway




