name: deploy order order-backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout github
        uses: actions/checkout@v2
      - name: install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.25.9"
        id: install
      - name: configure aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_KEY}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET}}
          aws-region: ap-southeast-2

      - name: update cluster information
        run: aws eks update-kubeconfig --name my-cluster --region ap-southeast-2

      - name: Login to ECR
        id: login-ecr
        uses: aws-action/amazon-ecr-login@v1

      - name: gateway build and push docker image to ecr
        env:
          REGISTRY: 221082171363.dkr.ecr.ap-southeast-2.amazonaws.com
          REPOSITORY: apigateway
          IMAGE_TAG: latest
        run: |
          docker build \
          -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
          -f ./apigateway/apigateway/Dockerfile ./apigateway/apigateway
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
      - name: eks kubectl apply
        run: |
          kubectl apply -f ./apigateway/apigateway/k8s/depl_svc.yml
          kubectl rollout restart deployment apigateway-depl -n dev

      - name: member build and push docker image to ecr
        env:
          REGISTRY: 221082171363.dkr.ecr.ap-southeast-2.amazonaws.com
          REPOSITORY: member-service
          IMAGE_TAG: latest
        run: |
          docker build \
          -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
          -f ./member/member/Dockerfile ./member/member
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TYG
      - name: eks kubectl apply
        run: |
          kubectl apply -f ./member/member/k8s/depl_svc.yml
          kubectl rollout restart deployment member-depl -n dev

      - name: order build and push docker image to ecr
        env:
          REGISTRY: 221082171363.dkr.ecr.ap-southeast-2.amazonaws.com
          REPOSITORY: ordering-service
          IMAGE_TAG: latest
        run: |
          docker build \
          -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
          -f ./ordering/ordering/Dockerfile ./ordering/ordering
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TYG
      - name: eks kubectl apply
        run: |
          kubectl apply -f ./ordering/ordering/k8s/depl_svc.yml
          kubectl rollout restart deployment ordering-depl -n dev

      - name: product build and push docker image to ecr
        env:
          REGISTRY: 221082171363.dkr.ecr.ap-southeast-2.amazonaws.com
          REPOSITORY: product-service
          IMAGE_TAG: latest
        run: |
          docker build \
          -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
          -f ./product/product/Dockerfile ./product/product
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TYG

      - name: eks kubectl apply
        run : |
          kubectl apply -f ./product/product/k8s/depl_svc.yml
          kubectl rollout restart deployment product-depl -n dev

          

          
